import { Transaction } from '@/app/../modules/transaction-history/components/columns';

export const transactions: Transaction[] = [
	{
		id: 1,
		branch_id: 2,
		room_number: 12,
		room_name: 'Abyss',
		service_option: 'onsite visit',
		appointment_date: '2025-06-23T18:21:04Z',
		transaction_status: 'Visited',
		lessor_name: 'John Doe',
	},
	{
		id: 2,
		branch_id: 1,
		room_number: 5,
		room_name: 'Ocean View',
		service_option: 'onsite visit',
		appointment_date: '2025-06-24T11:30:00Z',
		transaction_status: 'Pending',
		lessor_name: 'Jane Smith',
	},
	{
		id: 3,
		branch_id: 3,
		room_number: 7,
		room_name: 'Mountain View',
		service_option: 'room reservation',
		appointment_date: '2025-06-25T14:00:00Z',
		transaction_status: 'Reserved',
		lessor_name: 'Alice Johnson',
	},
	{
		id: 4,
		branch_id: 2,
		room_number: 10,
		room_name: 'Skyline',
		service_option: 'onsite visit',
		appointment_date: '2025-06-26T09:45:00Z',
		transaction_status: 'Cancelled',
		lessor_name: 'Mark Wilson',
	},
	{
		id: 5,
		branch_id: 1,
		room_number: 3,
		room_name: 'Garden View',
		service_option: 'room reservation',
		appointment_date: '2025-06-27T16:00:00Z',
		transaction_status: 'Reserved',
		lessor_name: 'Emily Davis',
	},
];
